service: aws-iam-manager
provider:
  name: aws
  runtime: nodejs4.3

#Frankfurt
region: us-central-1

functions:
  hello:
    handler: index.handler
    events:
      - sns: GithubNotifyTopic

resources:
  Resources:
    # Create SNS Topic that will be used to catch messages from Github
    GithubNotifyTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: GithubNotifyTopic

    # Create Role that will be used to Push Messages on Githubs behalf
    GithubHookUser:
      Type: "AWS::IAM::User"
      Properties:
        UserName: GithubHookUser
        Policies:
          - PolicyName: GithubHookAllowSNSSubscriptionPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource:
                    Ref: GithubNotifyTopic

  Outputs:
    GithubNotifyTopicARN:
      Description: ARN of Github Hook topic, (SNS topic on GitHub)
      Value:
        Ref: GithubNotifyTopic
