service: aws-iam-manager
provider:
  name: aws
  runtime: nodejs4.3

region: us-east-1

functions:
  IAMManagerSNSHandler:
    handler: index.handler
    events:
      - sns:
          topicName: IAMManagerNotifyTopic
          displayName: IAMManagerNotifyTopic

resources:
  Resources:
    # Create Role that will be used to Push Messages on Githubs behalf
    IAMManagerUser:
      Type: "AWS::IAM::User"
      Properties:
        UserName: IAMManagerUser
        Policies:
          - PolicyName: IAMManagerGithubHookAllowSNSSubscriptionPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource:
                    Ref: SNSTopicIAMManagerNotifyTopic

  Outputs:
    IAMManagerNotifyTopicARN:
      Description: ARN of Github Hook topic, (SNS topic on GitHub)
      Value:
        Ref: SNSTopicIAMManagerNotifyTopic
